typeChart = {
    'Normal': {
        'Normal': 1,
        'Fire': 1,
        'Water': 1,
        'Electric': 1,
        'Grass': 1,
        'Ice': 1,
        'Fighting': 1,
        'Poison': 1,
        'Ground': 1,
        'Flying': 1,
        'Psychic': 1,
        'Bug': 1,
        'Rock': 1,
        'Ghost': 0,
        'Dragon': 1
    },
    'Fire': {
        'Normal': 1,
        'Fire': 1/2,
        'Water': 1/2,
        'Electric': 1,
        'Grass': 2,
        'Ice': 2,
        'Fighting': 1,
        'Poison': 1,
        'Ground': 1,
        'Flying': 1,
        'Psychic': 1,
        'Bug': 2,
        'Rock': 1/2,
        'Ghost': 1,
        'Dragon': 1/2
    },
    'Water': {
        'Normal': 1,
        'Fire': 2,
        'Water': 1/2,
        'Electric': 1,
        'Grass': 1/2,
        'Ice': 1,
        'Fighting': 1,
        'Poison': 1,
        'Ground': 2,
        'Flying': 1,
        'Psychic': 1,
        'Bug': 1,
        'Rock': 2,
        'Ghost': 1,
        'Dragon': 1/2
    },
    'Grass': {
        'Normal': 1,
        'Fire': 1/2,
        'Water': 2,
        'Electric': 1,
        'Grass': 1/2,
        'Ice': 1,
        'Fighting': 1,
        'Poison': 1/2,
        'Ground': 2,
        'Flying': 1/2,
        'Psychic': 1,
        'Bug': 1/2,
        'Rock': 2,
        'Ghost': 1,
        'Dragon': 1/2
    },
    'Poison': {
        'Water': 1
    }
}
